Repository laminas/automatic-releases, pull requests merged in 2020-08, with the labels that each got.

#28 Use US spelling for organization
  README.md
Labels: Documentation

#29 Update readme with latest changes
  README.md
Labels: Documentation

#30 Explain the needed scopes for the admin token
  README.md
Labels: Documentation

#18 Allow using existing Keep-A-Changelog files for release notes
  CHANGELOG.md
  bin/console.php
  composer.json
  composer.lock
  src/Application/Command/CreateMergeUpPullRequest.php
  src/Application/Command/ReleaseCommand.php
  src/Changelog/CommitReleaseChangelog.php
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Git/CommitFile.php
  src/Git/CommitFileViaConsole.php
  src/Github/ConcatenateMultipleReleaseTexts.php
  src/Github/CreateReleaseText.php
  src/Github/CreateReleaseTextThroughChangelog.php
  src/Github/CreateReleaseTextViaKeepAChangelog.php
  test/unit/Application/ReleaseCommandTest.php
  test/unit/Changelog/ReleaseChangelogViaKeepAChangelogTest.php
  test/unit/Git/CommitFileViaConsoleTest.php
  test/unit/Github/ConcatenateMultipleReleaseTextsTest.php
  test/unit/Github/CreateChangelogTextTest.php
  test/unit/Github/CreateReleaseTextViaKeepAChangelogTest.php
Labels: Enhancement, Review Needed

#36 Describe automatically create merge-up branches
  README.md
Labels: Documentation, Enhancement

#38 Update example workflow to reference `v1` as release version
  .github/workflows/update-major-release.yml
  examples/.github/workflows/release-on-milestone-closed.yml
Labels: Documentation, Enhancement

#39 Provide the ability to log to STDERR
  bin/console.php
  composer.json
  composer.lock
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Environment/EnvironmentVariables.php
  src/Environment/Variables.php
  test/unit/Changelog/ReleaseChangelogViaKeepAChangelogTest.php
Labels: Enhancement

#40 When a new release is made, bump the CHANGELOG version in the next release branch and the originating release branch
  .github/workflows/automatic-release.yml
  CHANGELOG.md
  bin/console.php
  examples/.github/workflows/release-on-milestone-closed.yml
  src/Application/Command/BumpChangelogForReleaseBranch.php
  src/Application/Command/SwitchDefaultBranchToNextMinor.php
  src/Changelog/BumpAndCommitChangelogVersion.php
  src/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelog.php
  src/Git/CheckoutBranch.php
  src/Git/CheckoutBranchViaConsole.php
  test/unit/Application/BumpChangelogForReleaseBranchTest.php
  test/unit/Application/ReleaseCommandTest.php
  test/unit/Application/SwitchDefaultBranchToNextMinorTest.php
  test/unit/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelogTest.php
  test/unit/Git/CheckoutBranchViaConsoleTest.php
Labels: Enhancement, Review Needed

#41 Do not checkout the branch passed to `CommitFileViaConsole`
  CHANGELOG.md
  src/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelog.php
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Git/CommitFile.php
  src/Git/CommitFileViaConsole.php
  test/unit/Git/CommitFileViaConsoleTest.php
Labels: Bug

#42 Update Dockerfile to have modern toolchain
  Dockerfile
Labels: Bug

#43 Fix which branch the minor release bump in the changelog targets.
  CHANGELOG.md
  src/Application/Command/SwitchDefaultBranchToNextMinor.php
  test/unit/Application/SwitchDefaultBranchToNextMinorTest.php
Labels: Bug

#45 Fix YAML config for actions-tagger workflow
  .github/workflows/update-major-release.yml
Labels: Bug

#47 Idempotent operations for reading, checkout branch prior to writing
  CHANGELOG.md
  bin/console.php
  src/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelog.php
  src/Changelog/ChangelogExists.php
  src/Changelog/ChangelogExistsViaConsole.php
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Github/CreateReleaseTextViaKeepAChangelog.php
  test/unit/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelogTest.php
  test/unit/Changelog/ChangelogExistsViaConsoleTest.php
  test/unit/Changelog/ReleaseChangelogViaKeepAChangelogTest.php
  test/unit/Github/CreateReleaseTextViaKeepAChangelogTest.php
Labels: Bug, Review Needed

#50 When using the REST API, send "token" authorization instead of "bearer"
  src/Github/Api/V3/CreatePullRequestThroughApiCall.php
  src/Github/Api/V3/CreateReleaseThroughApiCall.php
  src/Github/Api/V3/SetDefaultBranchThroughApiCall.php
  test/unit/Github/Api/V3/CreatePullRequestTest.php
  test/unit/Github/Api/V3/CreateReleaseTest.php
  test/unit/Github/Api/V3/SetDefaultBranchThroughApiCallTest.php
Labels: Bug

#53 Use ORGANIZATION_ADMIN_TOKEN for our own release action
  .github/workflows/automatic-release.yml
Labels: Bug

#54 Update workflow documentation and examples
  README.md
  examples/.github/workflows/release-on-milestone-closed.yml
Labels: Documentation

#55 Check for changelog and/or pull contents from changelog using remote origin
  CHANGELOG.md
  src/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelog.php
  src/Changelog/ChangelogExistsViaConsole.php
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Git/CommitFileViaConsole.php
  src/Github/CreateReleaseTextViaKeepAChangelog.php
  test/unit/Changelog/ChangelogExistsViaConsoleTest.php
  test/unit/Changelog/ReleaseChangelogViaKeepAChangelogTest.php
  test/unit/Github/CreateReleaseTextViaKeepAChangelogTest.php
Labels: Bug

#59 Remove redundant infection configuration
  infection.json.dist
Labels: Bug

#60 Updates README.md - automation is not laminas-specific
  README.md
Labels: Bug, Documentation

#58 Feature/changelog revisions
  CHANGELOG.md
  bin/console.php
  examples/.github/workflows/release-on-milestone-closed-triggering-release-event.yml
  src/Application/Command/CreateMergeUpPullRequest.php
  src/Application/Command/ReleaseCommand.php
  src/Changelog/ChangelogReleaseNotes.php
  src/Changelog/CommitReleaseChangelog.php
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Github/CreateReleaseText.php
  src/Github/CreateReleaseTextThroughChangelog.php
  src/Github/CreateReleaseTextViaKeepAChangelog.php
  src/Github/MergeMultipleReleaseNotes.php
  test/unit/Application/CreateMergeUpPullRequestTest.php
  test/unit/Application/ReleaseCommandTest.php
  test/unit/Changelog/ChangelogReleaseNotesTest.php
  test/unit/Changelog/ReleaseChangelogViaKeepAChangelogTest.php
  test/unit/Github/CreateChangelogTextTest.php
  test/unit/Github/CreateReleaseTextViaKeepAChangelogTest.php
  test/unit/Github/MergeMultipleReleaseNotesTest.php
Labels: Enhancement, Review Needed

#62 Add milestone descriptions
  src/Git/Value/SemVerVersion.php
  src/Github/Api/V3/CreateMilestoneThroughApiCall.php
  test/unit/Git/Value/SemVerVersionTest.php
  test/unit/Github/Api/V3/CreateMilestoneTest.php
Labels: Enhancement
