Repository laminas/automatic-releases, pull requests merged in 2020-09, with the labels that each got.

#66 End changelog version entry with empty line
  src/Changelog/ChangelogReleaseNotes.php
  test/unit/Changelog/ChangelogReleaseNotesTest.php
Labels: Enhancement

#67 Normalize generated text to strip extra lines and redundant version information
  src/Github/CreateReleaseTextThroughChangelog.php
  test/unit/Github/CreateChangelogTextTest.php
Labels: Enhancement

#68 Strip empty sections from keep-a-changelog release notes
  src/Github/CreateReleaseTextViaKeepAChangelog.php
  test/unit/Github/CreateReleaseTextViaKeepAChangelogTest.php
Labels: Enhancement

#69 Add all required environment variables to `release-on-milestone-close…
  examples/.github/workflows/release-on-milestone-closed.yml
Labels: Bug, Documentation

#71 docs: add note about how GITHUB_TOKEN is created
  README.md
  src/Github/CreateReleaseTextThroughChangelog.php
Labels: Documentation

#72 feat: sign commits, as well as tags
  src/Application/Command/BumpChangelogForReleaseBranch.php
  src/Application/Command/ReleaseCommand.php
  src/Application/Command/SwitchDefaultBranchToNextMinor.php
  src/Changelog/BumpAndCommitChangelogVersion.php
  src/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelog.php
  src/Changelog/CommitReleaseChangelog.php
  src/Changelog/CommitReleaseChangelogViaKeepAChangelog.php
  src/Git/CommitFile.php
  src/Git/CommitFileViaConsole.php
  test/unit/Application/BumpChangelogForReleaseBranchTest.php
  test/unit/Application/SwitchDefaultBranchToNextMinorTest.php
  test/unit/Changelog/BumpAndCommitChangelogVersionViaKeepAChangelogTest.php
  test/unit/Changelog/ReleaseChangelogViaKeepAChangelogTest.php
  test/unit/Git/CommitFileViaConsoleTest.php
Labels: Enhancement

#73 fix: update phly/keep-a-changelog
  composer.json
  composer.lock
Labels: Bug, Enhancement

#75 Fix docker actions name label
  Dockerfile
Labels: Documentation
