Repository laminas/automatic-releases, pull requests merged in 2020-07, with the labels that each got.

#2 update license in composer.json to BSD-3-Clause
  composer.json
Labels: Documentation, Enhancement

#3 Fix coding standard check
  src/Git/PushViaConsole.php
Labels: Bug

#7 Initial documentation for installation and usage of `laminas/automatic-releases`
  README.md
  action.yml
  examples/.github/workflows/release-on-milestone-closed.yml
Labels: Documentation

#10 #8 #9 disable adding `.git` during `Dockerfile` steps
  Dockerfile
Labels: Bug

#12 #11 - create+switch default branch on release
  .github/workflows/automatic-release.yml
  README.md
  action.yml
  bin/console.php
  examples/.github/workflows/release-on-milestone-closed.yml
  feature/automated-releases.feature
  feature/default-branch-switching.feature
  infection.json.dist
  src/Application/Command/SwitchDefaultBranchToNextMinor.php
  src/Git/Value/BranchName.php
  src/Git/Value/MergeTargetCandidateBranches.php
  src/Git/Value/SemVerVersion.php
  src/Github/Api/V3/SetDefaultBranch.php
  src/Github/Api/V3/SetDefaultBranchThroughApiCall.php
  test/unit/Application/SwitchDefaultBranchToNextMinorTest.php
  test/unit/Git/Value/BranchNameTest.php
  test/unit/Git/Value/MergeTargetCandidateBranchesTest.php
  test/unit/Git/Value/SemVerVersionTest.php
  test/unit/Github/Api/V3/SetDefaultBranchThroughApiCallTest.php
Labels: Enhancement

#17 Corrected released action format - must be same as tags
  examples/.github/workflows/release-on-milestone-closed.yml
Labels: Bug
