Repository laminas/automatic-releases, pull requests merged in 2021-02, with the labels that each got.

#113 Fix workflow trigger
  .github/workflows/coding-standards.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
Labels: Enhancement

#116 Fix version comparison algorithm
  src/Git/Value/SemVerVersion.php
  test/unit/Git/Value/SemVerVersionTest.php
Labels: Bug

#102 Improve documentation for gpg subkey creation
  README.md
Labels: Documentation, Enhancement

#115 Reduce docker image size (and build time)
  .github/workflows/docker-build.yml
  Dockerfile
Labels: Enhancement

#117 reduce semver version comparison complixity
  src/Git/Value/SemVerVersion.php
Labels: Enhancement

#118 Fix mutation test flow for branches/tags
  .github/workflows/mutation-tests.yml
Labels: Bug
