Repository laminas/automatic-releases, pull requests merged in 2021-01, with the labels that each got.

#97 Upgraded dependencies, `composer:^2` and `php:^8`, mutation tests CI improvements
  .github/workflows/coding-standards.yml
  .github/workflows/docker-build.yml
  .github/workflows/mutation-tests.yml
  .github/workflows/phpunit.yml
  .github/workflows/psalm.yml
  Dockerfile
  bin/console.php
  composer.json
  composer.lock
  infection.json.dist
  phpunit.xml.dist
  src/Changelog/ChangelogReleaseNotes.php
Labels: Awaiting Author Updates, Enhancement

#100 Replace bash wrapper for entrypoint
  Dockerfile
  entrypoint.sh
Labels: Bug

#101 Add setting up gpg keys link to SIGNING_SECRET_KEY
  README.md
Labels: Documentation, Enhancement

#104 Docs clarification on ORGANIZATION_ADMIN_TOKEN for non-organization accounts
  README.md
Labels: Documentation, Enhancement

#103 README: Do not add all possible workflows
  README.md
Labels: Documentation, Enhancement
