Repository laminas/automatic-releases, pull requests merged in 2021-05, with the labels that each got.

#125 Set shell verbosity to debug by default
  Dockerfile
Labels: Enhancement, Feature Request

#136 Normalize composer
  composer.json
Labels: Enhancement, dependencies

#140 Private repository release support
  bin/console.php
  src/Github/JwageGenerateChangelog.php
  test/unit/Github/JwageGenerateChangelogTest.php
Labels: Bug
